### ISSUE TITLE
Crash while starting

### ISSUE THREAD

**Issue by ashmodai6** [korylprince/hassio-node-red#11]
seems this issue is still not resolved .... Running 1.8
31 Mar 22:59:30 - [red] Uncaught Exception:
31 Mar 22:59:30 - TypeError: Cannot read property 'state' of null
    at ServerStateChangedNode.onHaEventsStateChanged (/share/node-red/node_modules/node-red-contrib-home-assistant/nodes/server-events-state-changed/server-events-state-changed.js:38:42)
    at emitOne (events.js:121:20)
    at HaEvents.emit (events.js:211:7)
    at HaEvents.onClientMessage (/share/node-red/node_modules/node-home-assistant/lib/ha-events.js:59:22)
    at EventSource.client.on (/share/node-red/node_modules/node-home-assistant/lib/ha-events.js:27:49)
    at emitOne (events.js:116:13)
    at EventSource.emit (events.js:211:7)
    at _emit (/share/node-red/node_modules/eventsource/lib/eventsource.js:222:17)
    at parseEventStreamLine (/share/node-red/node_modules/eventsource/lib/eventsource.js:237:9)
    at IncomingMessage.<anonymous> (/share/node-red/node_modules/eventsource/lib/eventsource.js:200:11)

**Comment by wwolkers** [comment]
This is actually a home-assitant issue, hass is sending a null value which it should not.
There is already an open issue for this at the node-red-contrib-home-assistant github (https://github.com/AYapejian/node-red-contrib-home-assistant/issues/44) which includes a fix for the crash, but the real problem should be solved in hass also!

**Comment by AYapejian** [comment]
[#44](https://github.com/AYapejian/node-red-contrib-home-assistant/issues/44) merged and released

**Comment by korylprince** [comment]
Thanks for the fix! I've released 1.9 which bundles 0.3.2.
